demo.message=Hello from DEV profile

server.servlet.session.timeout=1

#demo.name=Nitin

demo.first.enabled=false

user.min.role.length=5
user.max.role.length=20

#All users can access the Togglz Admin Console, but make it secured in production
togglz.console.secured=false

# Explicitly enable the console
togglz.console.enabled=true
togglz.console.path=/togglz-console

# docker run -d --name my-redis -p 6379:6379 redis:8.4.2-alpine3.22
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.redis.key-prefix=togglz-
#spring.cache.redis.time-to-live=5s # this timeout doesn't work with RedisStateRepository, so no use here.
spring.cache.redis.use-key-prefix=true