demo.message=Hello from DEV profile

server.servlet.session.timeout=1

#demo.name=Nitin

demo.first.enabled=false

user.min.role.length=5
user.max.role.length=20

#All users can access the Togglz Admin Console, but make it secured in production
togglz.console.secured=false

# Explicitly enable the console
togglz.console.enabled=true
togglz.console.path=/togglz-console