spring.application.name=demo-observability-app
server.port=8080

spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted

management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=1.0.0

spring.cache.cache-names=Values

spring.mvc.problemdetails.enabled=true

spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# enable H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Group APIs by controller/package (optional)
springdoc.packages-to-scan=com.example.demo.controller
springdoc.paths-to-match=/api/**

# Logging configuration
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.example.demoobservabilityapp=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.boot.actuate.metrics=DEBUG
logging.level.io.micrometer=DEBUG
logging.level.org.liquibase=INFO
logging.level.org.springframework.boot.autoconfigure.liquibase=INFO
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
